#!/bin/bash

. /etc/rc.d/functions

case "$1" in
    start)
        stat_busy "Starting fancontrol script"
        [ ! -f /var/run/daemons/fancontrol ] && /usr/local/bin/fancontrol --daemon
        if [ $? -gt 0 ]; then
            stat_fail
        else
            add_daemon rsyncd
            stat_done
        fi
        ;;
    stop)
        stat_busy "Stopping the fancontrol script"
        [ -f /var/run/fancontrol.pid ] && kill `cat /var/run/fancontrol.pid`
        if [ $? -gt 0 ]; then
            stat_fail
        else
            rm -f /var/run/fancontrol.pid
            rm_daemon fancontrol
            stat_done
        fi
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "usage: $0 {start|stop|restart}"
esac
exit 0