#!/usr/bin/tclsh

# Stupid fan control script that simply blasts the fans when the
# temperature reaches a certain level.

# 2 minutes
set interval 12000
set pidfile "/var/run/fancontrol.pid"

proc gettemp {} {
    set tempsens "/proc/acpi/ibm/thermal"
    return [lindex [split [exec cat $tempsens]] 1]
}

proc controlfan {temp} {
    set threshold 75
    set fansens "/proc/acpi/ibm/fan"

    if {$temp < $threshold} {
        exec echo level auto > $fansens
    } else {
        exec echo level full-speed > $fansens
    }
}


# If started as a daemon, fork to background
if {$argc > 0 && [lindex $argv 0] == "--daemon"} {
    if {[expr {![file exists $pidfile]}] || [expr {[file size $pidfile] == 0}]} {
        set pid [exec $argv0 >/dev/null &]

        exec echo $pid > $pidfile

        exit 0
    } else {
        puts "fancontrol is already running in daemon mode."

        exit 1
    }
}

while {1} {
    controlfan [gettemp]
    
    after $interval
}