#!/usr/bin/tclsh

# Stupid fan control script that simply blasts the fans when the
# temperature reaches a certain level.

# 2 minutes
set interval 12000
set threshold 75
set fansens "/proc/acpi/ibm/fan"
set tempsens "/proc/acpi/ibm/thermal"
set pidfile "/var/run/fancontrol.pid"

# If started as a daemon, fork to background
if {$argc > 0 && [lindex $argv 0] == "--daemon"} {
    if {![file exists $pidfile]} {
        set pid [exec $argv0 >/dev/null &]

        exec echo $pid > $pidfile

        exit 0
    } else {
        puts "fancontrol is already running in daemon mode."

        exit 1
    }
}

# Resets the level at the beginning
exec echo level auto > $fansens

set fullspeed 0

while {1} {
    # Get the temperature
    set temp [lindex [split [exec cat $tempsens]] 1]

    # Set the temperature
    set lthreshold $threshold
    if {$fullspeed} {
        set lthreshold [expr {$threshold - 10}]
    }
    
    if {$temp < $lthreshold} {
        exec echo level auto > $fansens
        set fullspeed 0
    } else {
        exec echo level full-speed > $fansens
        set fullspeed 1
    }

    # Wait
    after $interval
}